### PR TITLE
Fix data race in NodeManager

### LINKED ISSUE #3574: Data race condition in NodeManager
Analysis with LLVM Clang/OpenMP/Archer shows a data race in `NodeManager::ensure_valig_thread_local_ids()` between reading `wfr_network_size_` here https://github.com/nest/nest-simulator/blob/83713a2854fa0553c7247dea3c472e6ce7485e3d/nestkernel/node_manager.cpp#L532 and writing it here https://github.com/nest/nest-simulator/blob/83713a2854fa0553c7247dea3c472e6ce7485e3d/nestkernel/node_manager.cpp#L577.

The solution is to no longer call this method, which is entirely related to nodes, from parallel context during connection creation, but to make sure that local ids are updated before entering parallel connection creation.

In a connection context, this method is until now only called from here https://github.com/nest/nest-simulator/blob/83713a2854fa0553c7247dea3c472e6ce7485e3d/nestkernel/target_identifier.h#L171 when creating `_hpc` synapses, so any testing must be based on such synapses. `hpc_benchmark.sli` lead to the discovery of this bug.

### PR DESCRIPTION
**Pull request by heplesser**
This PR fixes #3574 by moving the check for updated thread-local data structures from `TargetIdentifierIndex::set_target()`,  which is called very deeply in the creation of every single connection in parallel context, out to top-level connection code (just below the level of the functions in `NestModule`). This makes sense, because this update is only related to nodes, not to connections. `set_target()` only requires that each node knows its up-to-date local node id.

In the process I have also renamed some variables and methods, because the code affected here does more than just update WFR-related data structures.

I realize that the code in https://github.com/heplesser/nest-simulator/blob/18e75eecf33f291bf2602eac843772bfb0918ef0/nestkernel/node_manager.cpp#L526 is not ideal. We should be able to eliminate at least the last loop over the local nodes and we could probably let the loop over the threads run in parallel. But that needs to come at a later stage due to time constraints.

I also realize that we should try to integrate this thread-local-is-up-to-date with the `have_nodes_changed` checks, but also that will take extra time.

### CODE REVIEW

File: nestkernel/nest.cpp [hunk 1]
```diff
@@ -221,6 +221,9 @@ get_connections( const DictionaryDatum& dict )
 void
 disconnect( const ArrayDatum& conns )
 {
+  // probably not strictly necessarye here, but does nothing if all is up to date
```
Comment (suku248) [inline nestkernel/nest.cpp]: typo "necessary"

Comment (heplesser) [reply nestkernel/nest.cpp]: Fixed.

File: nestkernel/node_manager.h [hunk 2]
```diff
@@ -401,6 +411,15 @@ NodeManager::set_have_nodes_changed( const bool changed )
   have_nodes_changed_ = changed;
 }
 
+inline bool
+NodeManager::thread_local_data_is_up_to_date() const
+{
+  // Our logic assumes that we never delete nodes from a network
+  assert( size() >= size_last_local_data_update_ );
```
Comment (JoseJVS) [inline nestkernel/node_manager.h:418]: Why not directly assert size() == size_last... Since anyways the result will be used in an assertion when returned?

Comment (heplesser) [reply nestkernel/node_manager.h:418]: We cannot assert equality here: New nodes may have been added since the last call, and then `size()` is larger than `size_last_local_data_update_`.
