### PR TITLE
Fix SLI sleep function (fixes #973)

### LINKED ISSUE #973: SLI sleep implementation conforming to standards?
@heplesser requested to create an issue:
It is rather surprising that no-one else has run into this issue:
```
[ 16%] Building CXX object sli/CMakeFiles/sli_lib.dir/slidata.cc.o
/Users/ehagen/Repositories/nest-simulator/sli/slicontrol.cc:1725:30: error: non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in
   initializer list [-Wc++11-narrowing]
struct timeval tv = { sec, usec };
                          ^~~~
```
In Sleep_dFunction::execute( SLIInterpreter* i ), usec is defined as long, but the POSIX standard only requires an "signed integer type capable of storing values at least in the range [-1, 1000000]", and on OSX it is of type int.

C++98 didn't care about the narrow, C++11 does. The way this SLI-sleep functions is implemented using the POSIX select() function also seems archaic. There is POSIX usleep() and since C++11 even std::this_thread::sleep_for.

Encountered on MacOS with Anaconda Python and conda's mpi compilers:
```
I think I found a new and interesting way to break the compilation of NEST, this time with Anaconda Python 3 (most recent) on my mac (v10.13.5):
$ conda -V
conda 4.5.4
$ python -V
Python 3.6.5

I’ve tried to use dependencies and compilers as provided by Anaconda and conda-forge to keep things self contained;
$ conda config --add channels conda-forge
$ conda install openmpi readline pkg-config gsl doxygen cmake #and probably others

Nest installation procedure (master@ad52581ce7):
$ export CC=~/anaconda3/bin/mpicc
$ export CXX=~/anaconda3/bin/mpicxx

$ export NESTBLD=$HOME/Repositories/nest-simulator-bld
$ export NESTSOURCES=$HOME/Repositories/nest-simulator
$ export NESTPREFIX=$HOME/.local/nest_py36

$ mkdir $NESTBLD
$ cd $NESTBLD

$ cmake -DCMAKE_INSTALL_PREFIX:PATH=$NESTPREFIX \
    -Dwith-mpi=ON \
    -Dwith-python=ON \
    -DLTDL_ROOT_DIR=~/anaconda3 -Dwith-gsl=~/anaconda3 -Dwith-readline=~/anaconda3 \
    -DCMAKE_C_COMPILER=$CC \
    -DCMAKE_CXX_COMPILER=$CXX \
    $NESTSOURCES


Which gives (looks fine to me, except OpenMP is not found - don’t think it is crucial):
-- The CXX compiler identification is Clang 6.0.0
-- The C compiler identification is Clang 6.0.0
-- Check for working CXX compiler: /Users/ehagen/anaconda3/bin/mpicxx
-- Check for working CXX compiler: /Users/ehagen/anaconda3/bin/mpicxx -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Check for working C compiler: /Users/ehagen/anaconda3/bin/mpicc
-- Check for working C compiler: /Users/ehagen/anaconda3/bin/mpicc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Found Doxygen: /Users/ehagen/anaconda3/bin/doxygen (found version "1.8.14") found components:  doxygen dot 
-- Looking for include file inttypes.h
-- Looking for include file inttypes.h - found
-- Looking for include file mach-o/dyld.h
-- Looking for include file mach-o/dyld.h - found
-- Looking for include file mach/mach.h
-- Looking for include file mach/mach.h - found
-- Looking for include file memory.h
-- Looking for include file memory.h - found
-- Looking for include file stdint.h
-- Looking for include file stdint.h - found
-- Looking for include file sys/types.h
-- Looking for include file sys/types.h - found
-- Looking for C++ include istream
-- Looking for C++ include istream - found
-- Looking for C++ include ostream
-- Looking for C++ include ostream - found
-- Looking for C++ include sstream
-- Looking for C++ include sstream - found
-- Looking for stddef.h
-- Looking for stddef.h - found
-- Check size of long long
-- Check size of long long - done
-- Check size of u_int16_t
-- Check size of u_int16_t - failed
-- Check size of uint16_t
-- Check size of uint16_t - done
-- Looking for NAN
-- Looking for NAN - found
-- Looking for isnan
-- Looking for isnan - found
-- Looking for M_E
-- Looking for M_E - found
-- Looking for M_PI
-- Looking for M_PI - found
-- Looking for expm1
-- Looking for expm1 - found
-- Host triple: x86_64-apple-darwin
-- Target triple: x86_64-apple-darwin
-- Found LTDL: /Users/ehagen/anaconda3/lib/libltdl.dylib (found version "2.4.6") 
-- Found Readline: /Users/ehagen/anaconda3/lib/libreadline.dylib (found version "7.0") 
-- Found PkgConfig: /Users/ehagen/anaconda3/bin/pkg-config (found version "0.29.2") 
-- Found GSL: /Users/ehagen/anaconda3/include (found version "2.1") 
-- Found PythonInterp: /Users/ehagen/anaconda3/bin/python (found version "3.6.5") 
-- Found PythonLibs: /Users/ehagen/anaconda3/lib/libpython3.6m.dylib (found suitable exact version "3.6.5") 
-- Found Cython: /Users/ehagen/anaconda3/bin/cython (found version "0.28.3") 
-- Could NOT find OpenMP_C (missing: OpenMP_C_FLAGS OpenMP_C_LIB_NAMES) 
-- Could NOT find OpenMP_CXX (missing: OpenMP_CXX_FLAGS OpenMP_CXX_LIB_NAMES) 
-- Could NOT find OpenMP (missing: OpenMP_C_FOUND OpenMP_CXX_FOUND) 
-- Found MPI_C: /Users/ehagen/anaconda3/bin/mpicc (found version "3.1") 
-- Found MPI_CXX: /Users/ehagen/anaconda3/bin/mpicxx (found version "3.1") 
-- Found MPI: TRUE (found version "3.1")  
-- Check the abort exitcode.
-- Check the abort exitcode. 134
-- Check the segmentation fault exitcode.
-- Check the segmentation fault exitcode. 134
-- Check whether the compiler ignores cmath makros.
-- Check whether the compiler ignores cmath makros. OFF
-- Check whether the compiler does NOT include <*.h> headers ISO conformant.
-- Check whether the compiler does NOT include <*.h> headers ISO conformant. OFF
-- Check whether the compiler respects symbolic signal names in signal.h.
-- Check whether the compiler respects symbolic signal names in signal.h. OFF
-- Check static template member declaration.
-- Check static template member declaration. OFF
-- Check for STL vector capacity base unity.
-- Check for STL vector capacity base unity. OFF
-- Check for STL vector capacity doubling strategy.
-- Check for STL vector capacity doubling strategy. OFF
-- Check whether the compiler fails with ICE.
-- Check whether the compiler fails with ICE. OFF
-- Check if ::nan is available from cmath.
-- Check if ::nan is available from cmath. ON
-- Check if ::isnan is available from cmath.
-- Check if ::isnan is available from cmath. ON
ad52581c
-- Found PythonLibs: /Users/ehagen/anaconda3/lib/libpython3.6m.dylib (found version "3.6.5") 

--------------------------------------------------------------------------------
NEST Configuration Summary
--------------------------------------------------------------------------------

Build type          : 
Target System       : Darwin
Cross Compiling     : FALSE
C compiler          : /Users/ehagen/anaconda3/bin/mpicc
C compiler flags    :  -O2 -Wall    
C++ compiler        : /Users/ehagen/anaconda3/bin/mpicxx
C++ compiler flags  :  -O2 -Wall  
Build dynamic       : ON

Built-in modules    : models;precise;topology
User modules        : None
Python bindings     : Yes (Python 3.6: /Users/ehagen/anaconda3/bin/python)
     Includes     : /Users/ehagen/anaconda3/include/python3.6m
     Libraries    : /Users/ehagen/anaconda3/lib/libpython3.6m.dylib

Cython bindings     : Yes (Cython 0.28.3: /Users/ehagen/anaconda3/bin/cython)
Use threading       : No
Use GSL             : Yes (GSL 2.1)
  Includes        : /Users/ehagen/anaconda3/include
  Libraries       : /Users/ehagen/anaconda3/lib/libgsl.dylib;/Users/ehagen/anaconda3/lib/libgslcblas.dylib

Use Readline        : Yes (GNU Readline 7.0)
  Includes        : /Users/ehagen/anaconda3/include
  Libraries       : /Users/ehagen/anaconda3/lib/libreadline.dylib;/Users/ehagen/anaconda3/lib/libncurses.dylib

Use libltdl         : Yes (LTDL 2.4.6)
  Includes        : /Users/ehagen/anaconda3/include
  Libraries       : /Users/ehagen/anaconda3/lib/libltdl.dylib

Use doxygen         : Yes (/Users/ehagen/anaconda3/bin/doxygen)
                  : target `doc` available
  `dot` available : Yes (/opt/local/bin/dot)
                  : target `fulldoc` available
Use MPI             : Yes (MPI: /Users/ehagen/anaconda3/bin/mpicxx)
  FLAGS           : 
  Includes        : 
  Link Flags      : 
  Libraries       : 

Use MUSIC           : No
Use libneurosim     : No

————————————————————————————————————————


But, make fails:
$ make -j4
Scanning dependencies of target nestutil
[  0%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/logging_event.cpp.o
[  0%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/numerics.cpp.o
[  0%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/stopwatch.cpp.o
[  1%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/propagator_stability.cpp.o
[  2%] Linking CXX shared library libnestutil.dylib
[  2%] Built target nestutil
Scanning dependencies of target sli_lib
[  3%] Building CXX object sli/CMakeFiles/sli_lib.dir/booldatum.cc.o
[  3%] Building CXX object sli/CMakeFiles/sli_lib.dir/charcode.cc.o
[  4%] Building CXX object sli/CMakeFiles/sli_lib.dir/arraydatum.cc.o
[  4%] Building CXX object sli/CMakeFiles/sli_lib.dir/allocator.cpp.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/datum.cc.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/dict.cc.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/dictdatum.cc.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/dictstack.cc.o
[  6%] Building CXX object sli/CMakeFiles/sli_lib.dir/dictutils.cc.o
[  6%] Building CXX object sli/CMakeFiles/sli_lib.dir/doubledatum.cc.o
[  7%] Building CXX object sli/CMakeFiles/sli_lib.dir/fdstream.cc.o
[  7%] Building CXX object sli/CMakeFiles/sli_lib.dir/filesystem.cc.o
[  7%] Building CXX object sli/CMakeFiles/sli_lib.dir/functiondatum.cc.o
[  8%] Building C object sli/CMakeFiles/sli_lib.dir/get_mem.c.o
[  8%] Building CXX object sli/CMakeFiles/sli_lib.dir/integerdatum.cc.o
[  9%] Building CXX object sli/CMakeFiles/sli_lib.dir/interpret.cc.o
[  9%] Building CXX object sli/CMakeFiles/sli_lib.dir/iostreamdatum.cc.o
[  9%] Building CXX object sli/CMakeFiles/sli_lib.dir/iteratordatum.cc.o
[ 10%] Building CXX object sli/CMakeFiles/sli_lib.dir/literaldatum.cc.o
[ 10%] Building CXX object sli/CMakeFiles/sli_lib.dir/name.cc.o
[ 11%] Building CXX object sli/CMakeFiles/sli_lib.dir/slinames.cpp.o
[ 11%] Building CXX object sli/CMakeFiles/sli_lib.dir/namedatum.cc.o
[ 11%] Building CXX object sli/CMakeFiles/sli_lib.dir/oosupport.cc.o
[ 12%] Building CXX object sli/CMakeFiles/sli_lib.dir/parser.cc.o
[ 12%] Building CXX object sli/CMakeFiles/sli_lib.dir/processes.cc.o
[ 13%] Building C object sli/CMakeFiles/sli_lib.dir/psignal.c.o
[ 13%] Building CXX object sli/CMakeFiles/sli_lib.dir/scanner.cc.o
[ 14%] Building CXX object sli/CMakeFiles/sli_lib.dir/sli_io.cc.o
[ 14%] Building CXX object sli/CMakeFiles/sli_lib.dir/sliactions.cc.o
[ 14%] Building CXX object sli/CMakeFiles/sli_lib.dir/sliarray.cc.o
[ 15%] Building CXX object sli/CMakeFiles/sli_lib.dir/slibuiltins.cc.o
[ 15%] Building CXX object sli/CMakeFiles/sli_lib.dir/slicontrol.cc.o
[ 16%] Building CXX object sli/CMakeFiles/sli_lib.dir/slidata.cc.o
/Users/ehagen/Repositories/nest-simulator/sli/slicontrol.cc:1725:30: error: non-constant-expression cannot be narrowed from type 'long' to '__darwin_suseconds_t' (aka 'int') in
    initializer list [-Wc++11-narrowing]
struct timeval tv = { sec, usec };
                           ^~~~
/Users/ehagen/Repositories/nest-simulator/sli/slicontrol.cc:1725:30: note: insert an explicit cast to silence this issue
struct timeval tv = { sec, usec };
                           ^~~~
                           static_cast<__darwin_suseconds_t>( )
[ 16%] Building CXX object sli/CMakeFiles/sli_lib.dir/slidict.cc.o
1 error generated.
make[2]: *** [sli/CMakeFiles/sli_lib.dir/slicontrol.cc.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [sli/CMakeFiles/sli_lib.dir/all] Error 2
make: *** [all] Error 2
```

### PR DESCRIPTION
**Pull request by heplesser**
Revise implementation of sleep to work correctly with 32-bit signed int; remove duplicity of implementation for int and double arg. This eliminates a warning about narrowing, which is an error in strict C++11.

Also, it seemed that sleep times given as doubles were not handled correctly in the past, e.g. 2.75 s.

This fixes #973.

### CODE REVIEW

File: sli/slicontrol.cc [hunk 1]
```diff
@@ -1680,51 +1685,32 @@ TimeFunction::execute( SLIInterpreter* i ) const
...
-  struct timeval tv = { sec, usec };
-  if ( usec > 0 )
+  if ( t < 0 )
+  {
+    throw BadParameterValue( "t >= 0 required." );
+  }
+  else if ( t > std::numeric_limits< int >::max() )
   {
+    throw BadParameterValue( String::compose(
+      "t < %1s required.", std::numeric_limits< int >::max() ) );
```
Comment (hakonsbm) [inline sli/slicontrol.cc]: Shouldn't it be `t <=`?

Comment (heplesser) [reply sli/slicontrol.cc]: The limit is around 68 years (for 32-bit int), so I think it does not really matter much and avoids any potential corner cases. Therefore, I chose the simpler `<`.

Comment (hakonsbm) [reply sli/slicontrol.cc]: Alright :+1:

**Comment by heplesser** [comment]
@espenhgn Could you check if this works for you?

**Comment by espenhgn** [comment]
Hi,
Following my procedure from earlier; this change set results in other warnings and finally an error (while it takes care of the sleep function):
```
$ make
[  0%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/stopwatch.cpp.o
[  0%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/numerics.cpp.o
[  1%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/propagator_stability.cpp.o
[  1%] Building CXX object libnestutil/CMakeFiles/nestutil.dir/logging_event.cpp.o
[  2%] Linking CXX shared library libnestutil.dylib
[  2%] Built target nestutil
[  2%] Building CXX object sli/CMakeFiles/sli_lib.dir/allocator.cpp.o
[  3%] Building CXX object sli/CMakeFiles/sli_lib.dir/arraydatum.cc.o
[  3%] Building CXX object sli/CMakeFiles/sli_lib.dir/booldatum.cc.o
[  4%] Building CXX object sli/CMakeFiles/sli_lib.dir/charcode.cc.o
[  4%] Building CXX object sli/CMakeFiles/sli_lib.dir/datum.cc.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/dict.cc.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/dictdatum.cc.o
[  5%] Building CXX object sli/CMakeFiles/sli_lib.dir/dictstack.cc.o
[  6%] Building CXX object sli/CMakeFiles/sli_lib.dir/dictutils.cc.o
[  6%] Building CXX object sli/CMakeFiles/sli_lib.dir/doubledatum.cc.o
[  7%] Building CXX object sli/CMakeFiles/sli_lib.dir/fdstream.cc.o
[  7%] Building CXX object sli/CMakeFiles/sli_lib.dir/filesystem.cc.o
[  7%] Building CXX object sli/CMakeFiles/sli_lib.dir/functiondatum.cc.o
[  8%] Building C object sli/CMakeFiles/sli_lib.dir/get_mem.c.o
[  8%] Building CXX object sli/CMakeFiles/sli_lib.dir/integerdatum.cc.o
[  9%] Building CXX object sli/CMakeFiles/sli_lib.dir/interpret.cc.o
[  9%] Building CXX object sli/CMakeFiles/sli_lib.dir/iostreamdatum.cc.o
[  9%] Building CXX object sli/CMakeFiles/sli_lib.dir/iteratordatum.cc.o
[ 10%] Building CXX object sli/CMakeFiles/sli_lib.dir/literaldatum.cc.o
[ 10%] Building CXX object sli/CMakeFiles/sli_lib.dir/name.cc.o
[ 11%] Building CXX object sli/CMakeFiles/sli_lib.dir/slinames.cpp.o
[ 11%] Building CXX object sli/CMakeFiles/sli_lib.dir/namedatum.cc.o
[ 11%] Building CXX object sli/CMakeFiles/sli_lib.dir/oosupport.cc.o
[ 12%] Building CXX object sli/CMakeFiles/sli_lib.dir/parser.cc.o
[ 12%] Building CXX object sli/CMakeFiles/sli_lib.dir/processes.cc.o
[ 13%] Building C object sli/CMakeFiles/sli_lib.dir/psignal.c.o
[ 13%] Building CXX object sli/CMakeFiles/sli_lib.dir/scanner.cc.o
[ 14%] Building CXX object sli/CMakeFiles/sli_lib.dir/sli_io.cc.o
[ 14%] Building CXX object sli/CMakeFiles/sli_lib.dir/sliactions.cc.o
[ 14%] Building CXX object sli/CMakeFiles/sli_lib.dir/sliarray.cc.o
[ 15%] Building CXX object sli/CMakeFiles/sli_lib.dir/slibuiltins.cc.o
[ 15%] Building CXX object sli/CMakeFiles/sli_lib.dir/slicontrol.cc.o
[ 16%] Building CXX object sli/CMakeFiles/sli_lib.dir/slidata.cc.o
[ 16%] Building CXX object sli/CMakeFiles/sli_lib.dir/slidict.cc.o
[ 16%] Building CXX object sli/CMakeFiles/sli_lib.dir/sliexceptions.cc.o
[ 17%] Building CXX object sli/CMakeFiles/sli_lib.dir/sligraphics.cc.o
[ 17%] Building CXX object sli/CMakeFiles/sli_lib.dir/slimath.cc.o
[ 18%] Building CXX object sli/CMakeFiles/sli_lib.dir/slimodule.cc.o
[ 18%] Building CXX object sli/CMakeFiles/sli_lib.dir/sliregexp.cc.o
[ 18%] Building CXX object sli/CMakeFiles/sli_lib.dir/slistack.cc.o
[ 19%] Building CXX object sli/CMakeFiles/sli_lib.dir/slistartup.cc.o
[ 19%] Building CXX object sli/CMakeFiles/sli_lib.dir/slitype.cc.o
[ 20%] Building CXX object sli/CMakeFiles/sli_lib.dir/slitypecheck.cc.o
[ 20%] Building CXX object sli/CMakeFiles/sli_lib.dir/specialfunctionsmodule.cc.o
[ 20%] Building CXX object sli/CMakeFiles/sli_lib.dir/stringdatum.cc.o
[ 21%] Building CXX object sli/CMakeFiles/sli_lib.dir/symboldatum.cc.o
[ 21%] Building CXX object sli/CMakeFiles/sli_lib.dir/tarrayobj.cc.o
[ 22%] Building CXX object sli/CMakeFiles/sli_lib.dir/token.cc.o
[ 22%] Building CXX object sli/CMakeFiles/sli_lib.dir/tokenarray.cc.o
[ 23%] Building CXX object sli/CMakeFiles/sli_lib.dir/tokenstack.cc.o
[ 23%] Building CXX object sli/CMakeFiles/sli_lib.dir/tokenutils.cc.o
[ 23%] Building CXX object sli/CMakeFiles/sli_lib.dir/triedatum.cc.o
[ 24%] Building CXX object sli/CMakeFiles/sli_lib.dir/typechk.cc.o
[ 24%] Building CXX object sli/CMakeFiles/sli_lib.dir/utils.cc.o
[ 25%] Linking CXX shared library libsli.dylib
[ 25%] Built target sli_lib
[ 25%] Building CXX object librandom/CMakeFiles/random.dir/binomial_randomdev.cpp.o
[ 26%] Building CXX object librandom/CMakeFiles/random.dir/exp_randomdev.cpp.o
[ 26%] Building CXX object librandom/CMakeFiles/random.dir/gamma_randomdev.cpp.o
[ 27%] Building CXX object librandom/CMakeFiles/random.dir/gsl_binomial_randomdev.cpp.o
[ 27%] Building CXX object librandom/CMakeFiles/random.dir/gslrandomgen.cpp.o
[ 27%] Building CXX object librandom/CMakeFiles/random.dir/knuthlfg.cpp.o
[ 28%] Building CXX object librandom/CMakeFiles/random.dir/librandom_names.cpp.o
[ 28%] Building CXX object librandom/CMakeFiles/random.dir/lognormal_randomdev.cpp.o
[ 29%] Building CXX object librandom/CMakeFiles/random.dir/mt19937.cpp.o
[ 29%] Building CXX object librandom/CMakeFiles/random.dir/normal_randomdev.cpp.o
[ 30%] Building CXX object librandom/CMakeFiles/random.dir/poisson_randomdev.cpp.o
[ 30%] Building CXX object librandom/CMakeFiles/random.dir/random.cpp.o
[ 30%] Building CXX object librandom/CMakeFiles/random.dir/random_numbers.cpp.o
[ 31%] Building CXX object librandom/CMakeFiles/random.dir/randomdev.cpp.o
[ 31%] Building CXX object librandom/CMakeFiles/random.dir/randomgen.cpp.o
[ 32%] Building CXX object librandom/CMakeFiles/random.dir/uniform_randomdev.cpp.o
[ 32%] Building CXX object librandom/CMakeFiles/random.dir/uniformint_randomdev.cpp.o
[ 32%] Linking CXX shared library librandom.dylib
[ 32%] Built target random
[ 33%] Building CXX object librandom/CMakeFiles/randomtest.dir/randomtest.cpp.o
[ 33%] Linking CXX executable randomtest
[ 33%] Built target randomtest
[ 34%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/archiving_node.cpp.o
[ 34%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/common_synapse_properties.cpp.o
[ 34%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/sibling_container.cpp.o
[ 35%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/subnet.cpp.o
[ 35%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/connector_base.cpp.o
[ 36%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/connector_model.cpp.o
[ 36%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/connection_id.cpp.o
[ 36%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/device.cpp.o
[ 37%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/dynamicloader.cpp.o
[ 37%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/event.cpp.o
[ 38%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/exceptions.cpp.o
[ 38%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/gid_collection.cpp.o
[ 38%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/histentry.cpp.o
[ 39%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/model.cpp.o
[ 39%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/model_manager.cpp.o
[ 40%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nest_datums.cpp.o
[ 40%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nest_names.cpp.o
[ 41%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nestmodule.cpp.o
[ 41%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nest_time.cpp.o
[ 41%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nest_timeconverter.cpp.o
[ 42%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/modelrange.cpp.o
[ 42%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/modelrange_manager.cpp.o
[ 43%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/multirange.cpp.o
[ 43%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/node.cpp.o
[ 43%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nodelist.cpp.o
[ 44%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/proxynode.cpp.o
[ 44%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/recording_device.cpp.o
[ 45%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/ring_buffer.cpp.o
[ 45%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/spikecounter.cpp.o
[ 45%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/sparse_node_array.cpp.o
[ 46%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/conn_parameter.cpp.o
[ 46%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/conn_builder.cpp.o
[ 47%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/music_event_handler.cpp.o
[ 47%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/music_manager.cpp.o
[ 48%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/nest.cpp.o
In file included from /Users/ehagen/Repositories/nest-simulator/nestkernel/nest.cpp:31:
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:95:20: warning: instantiation of variable 'MPI_Type<long>::type' required here, but no definition is available
      [-Wundefined-var-template]
    MPI_Type< T >::type,
                   ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:139:7: note: in instantiation of function template specialization
      'nest::MPIManager::communicate_Allgatherv<long>' requested here
      communicate_Allgatherv< long >(
      ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/nest.cpp:385:26: note: in instantiation of function template specialization
      'nest::MPIManager::communicate<nest::LocalNodeListBase<nest::LocalNodeListIterator> >' requested here
    kernel().mpi_manager.communicate(
                         ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:82:23: note: forward declaration of template entity is here
  static MPI_Datatype type;
                      ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:95:20: note: add an explicit instantiation declaration to suppress this warning if 'MPI_Type<long>::type' is
      explicitly instantiated in another translation unit
    MPI_Type< T >::type,
                   ^
1 warning generated.
[ 48%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/synaptic_element.cpp.o
[ 48%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/growth_curve.cpp.o
[ 49%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/kernel_manager.cpp.o
[ 49%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/vp_manager.cpp.o
[ 50%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/io_manager.cpp.o
[ 50%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/mpi_manager.cpp.o
[ 50%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/simulation_manager.cpp.o
[ 51%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/connection_manager.cpp.o
In file included from /Users/ehagen/Repositories/nest-simulator/nestkernel/connection_manager.cpp:49:
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:95:20: warning: instantiation of variable 'MPI_Type<long>::type' required here, but no definition is available
      [-Wundefined-var-template]
    MPI_Type< T >::type,
                   ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:139:7: note: in instantiation of function template specialization
      'nest::MPIManager::communicate_Allgatherv<long>' requested here
      communicate_Allgatherv< long >(
      ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/connection_manager.cpp:873:26: note: in instantiation of function template specialization
      'nest::MPIManager::communicate<nest::LocalNodeListBase<nest::LocalLeafListIterator> >' requested here
    kernel().mpi_manager.communicate( local_sources, global_sources );
                         ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:82:23: note: forward declaration of template entity is here
  static MPI_Datatype type;
                      ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/mpi_manager_impl.h:95:20: note: add an explicit instantiation declaration to suppress this warning if 'MPI_Type<long>::type' is
      explicitly instantiated in another translation unit
    MPI_Type< T >::type,
                   ^
1 warning generated.
[ 51%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/sp_manager.cpp.o
[ 52%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/delay_checker.cpp.o
[ 52%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/rng_manager.cpp.o
[ 52%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/event_delivery_manager.cpp.o
[ 53%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/node_manager.cpp.o
[ 53%] Building CXX object nestkernel/CMakeFiles/nestkernel.dir/logging_manager.cpp.o
[ 54%] Linking CXX shared library libnestkernel.dylib
[ 54%] Built target nestkernel
[ 55%] Building CXX object models/CMakeFiles/models.dir/ac_generator.cpp.o
[ 55%] Building CXX object models/CMakeFiles/models.dir/aeif_cond_alpha.cpp.o
[ 56%] Building CXX object models/CMakeFiles/models.dir/aeif_cond_alpha_RK5.cpp.o
[ 56%] Building CXX object models/CMakeFiles/models.dir/aeif_cond_alpha_multisynapse.cpp.o
In file included from /Users/ehagen/Repositories/nest-simulator/models/aeif_cond_alpha_multisynapse.cpp:23:
In file included from /Users/ehagen/Repositories/nest-simulator/models/aeif_cond_alpha_multisynapse.h:38:
In file included from /Users/ehagen/Repositories/nest-simulator/nestkernel/archiving_node.h:41:
In file included from /Users/ehagen/Repositories/nest-simulator/nestkernel/node.h:35:
In file included from /Users/ehagen/Repositories/nest-simulator/nestkernel/event.h:36:
In file included from /Users/ehagen/Repositories/nest-simulator/nestkernel/exceptions.h:30:
In file included from /Users/ehagen/Repositories/nest-simulator/sli/name.h:30:
/Users/ehagen/anaconda3/include/c++/v1/map:629:15: error: object of type 'std::__1::pair<Name, const nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >' cannot be assigned
      because its copy assignment operator is implicitly deleted
        {__nc = __v.__cc; return *this;}
              ^
/Users/ehagen/anaconda3/include/c++/v1/__tree:1645:35: note: in instantiation of member function 'std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >::operator=' requested here
                __cache->__value_ = *__first;
                                  ^
/Users/ehagen/anaconda3/include/c++/v1/__tree:1575:9: note: in instantiation of function template specialization 'std::__1::__tree<std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >, std::__1::__map_value_compare<Name, std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >, std::__1::less<Name>, true>, std::__1::allocator<std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> > > >::__assign_multi<std::__1::__tree_const_iterator<std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >, std::__1::__tree_node<std::__1::__value_type<Name, const nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse>
      >, void *> *, long> >' requested here
        __assign_multi(__t.begin(), __t.end());
        ^
/Users/ehagen/anaconda3/include/c++/v1/map:912:21: note: in instantiation of member function 'std::__1::__tree<std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >, std::__1::__map_value_compare<Name, std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >, std::__1::less<Name>, true>, std::__1::allocator<std::__1::__value_type<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> > > >::operator=' requested here
            __tree_ = __m.__tree_;
                    ^
/Users/ehagen/Repositories/nest-simulator/nestkernel/recordables_map.h:183:7: note: in instantiation of member function 'std::__1::map<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse>, std::__1::less<Name>, std::__1::allocator<std::__1::pair<const Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> > > >::operator=' requested here
class DynamicRecordablesMap
      ^
/Users/ehagen/anaconda3/include/c++/v1/utility:325:5: note: copy assignment operator is implicitly deleted because 'pair<Name, const
      nest::DataAccessFunctor<nest::aeif_cond_alpha_multisynapse> >' has a user-declared move constructor
    pair(pair&&) = default;
    ^
1 error generated.
make[2]: *** [models/CMakeFiles/models.dir/aeif_cond_alpha_multisynapse.cpp.o] Error 1
make[1]: *** [models/CMakeFiles/models.dir/all] Error 2
make: *** [all] Error 2
```

**Comment by heplesser** [comment]
@espenhgn These are problems with newer C++ versions and here presumably libc++ instead of libstdc++. We need to modernize NEST code, see #974. There are a few more problems of this kind. As a work-around, you can try to use an older version of clang or use gcc.

File: sli/slicontrol.cc [hunk 2]
```diff
@@ -1680,51 +1685,32 @@ TimeFunction::execute( SLIInterpreter* i ) const
...
+  }
+  else if ( t > 0 )
+  {
```
Comment (jougs) [inline sli/slicontrol.cc]: I think this cascade of checks would be nicer and more readable if there were
* stand-alone `if`s for the checks, which `throw` in case of a parameter error (i.e. no `else if`s)
* no `else if` block at the end, but the code from that just behind the checks, thus rather having simpler code than treating the case of `t == 0` differently from `t > 0`. The overhead is probably negligible.

Comment (heplesser) [reply sli/slicontrol.cc]: @jougs Thank you for your feedback! I have now tidied the code as you suggested.

File: sli/slicontrol.cc [hunk 3]
```diff
@@ -1680,54 +1685,34 @@ TimeFunction::execute( SLIInterpreter* i ) const
...
   }
 
+  // split into second and microsecond part
+  // limited to 32-bit signed int, see #973.
+  const int t_sec = static_cast< int >( t );
+  const int t_musec = static_cast< int >( ( t - t_sec ) * 1e6 );
+
+  // on some systems, select may modify tv, therefore, it cannot be const
+  struct timeval tv = { t_sec, t_musec };
+  select( 0, 0, 0, 0, &tv );
```
Comment (jougs) [inline sli/slicontrol.cc]: On second thought, I find it a bit weird to use [`select`](https://en.wikipedia.org/wiki/Select_(Unix)) here instead of just
```C++
#include <unistd.h>
...
usleep(microseconds);
```
Can you please change (or at least comment on) this? Thanks!

**Comment by heplesser** [comment]
@jougs I now replaced `select()` with `sleep()` and `usleep()`. These sleep only the current thread, but since the SLI interpreter is single-threaded, this should not be any problem. I actually do not quite understand why we have `sleep` in SLI at all ...
