### PR TITLE
Moved check_synapse_params to specific synapse classes 

### LINKED ISSUE #737: Review `ConnBuilder::check_synapse_params_`
This is a follow-up to #735 and #736. `ConnBuilder::check_synapse_params_()` tests whether certain synapse parameters for certain synapse types. There are several problems with this code
- string passed by value, not reference;
- slow comparison with strings instead of Name objects;
- testing based on name of base model: tests will not be applied to copied models
- not sure if there is a unit- or regressiontest for all the tests performed here.

### PR DESCRIPTION
**Pull request by stinebuu**
This PR fixes #737 .

It takes each test in `ConnBuilder::check_synapse_params()` and moves it to a `check_synapse_params()` function in the respective synapse class. To make sure we don't have to add it to all the synapse classes, the `GenericConnectionModel` handles the allocation.

A regressiontest is also added, which make sure all tests fail if we send in the specific parameters in the syn_spec dictionary.

### CODE REVIEW

**Comment by heplesser** [comment]
@stinebuu All subtest in `issue-737.sli` that use threading should go into a separate file and be skipped if threading is not available.

**Comment by heplesser** [comment]
@kappeld Could you review this pull request? Since it adds the method `check_synapse_params()` to classes `ConnectorModel` and `Connection`, it may have an effect on your non-generic connector model. I particular, I think your connector model will have to implement the method.

File: models/cont_delay_connection.h [hunk 1]
```diff
@@ -141,6 +141,12 @@ class ContDelayConnection : public Connection< targetidentifierT >
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
+   * Check syn_spec dictionary for parameters that are not allowed for this
+   * connection. Will issue warning or throw error if a parameter is found.
```
Comment (heplesser) [inline models/cont_delay_connection.h]: - this general explanation should be in the base class only (`Connection`)
- here, you could just mention what is illegal for this particular synapse model
- Doxygen comments should begin with a single-line summary followed by details
- "an illegal parameter is found"
- add info that the method does nothing otherwise

File: models/quantal_stp_connection.h [hunk 2]
```diff
@@ -127,6 +127,12 @@ class Quantal_StpConnection : public Connection< targetidentifierT >
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
+   * Check syn_spec dictionary for parameters that are not allowed for this
+   * connection. Will issue warning or throw error if a parameter is found.
```
Comment (heplesser) [inline models/quantal_stp_connection.h]: See above.

File: models/static_connection_hom_w.h [hunk 3]
```diff
@@ -143,6 +143,21 @@ class StaticConnectionHomW : public Connection< targetidentifierT >
   }
 
   /**
+   * Check syn_spec dictionary for parameters that are not allowed for this
+   * connection. Will issue warning or throw error if a parameter is found.
+   */
```
Comment (heplesser) [inline models/static_connection_hom_w.h]: See above.

File: models/stdp_dopa_connection.h [hunk 4]
```diff
@@ -197,6 +197,12 @@ class STDPDopaConnection : public Connection< targetidentifierT >
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
+   * Check syn_spec dictionary for parameters that are not allowed for this
+   * connection. Will issue warning or throw error if a parameter is found.
+   */
```
Comment (heplesser) [inline models/stdp_dopa_connection.h]: See above.

File: nestkernel/conn_builder.cpp [hunk 5]
```diff
@@ -83,15 +83,14 @@ nest::ConnBuilder::ConnBuilder( const GIDCollection& sources,
...
-  if ( syn_name != "static_synapse" )
-  {
-    check_synapse_params_( syn_name, syn_spec );
-  }
-
   synapse_model_ = kernel().model_manager.get_synapsedict()->lookup( syn_name );
 
+  // We need to make sure that Connect can process all synapse parameters
+  // specified.
+  ConnectorModel& syn_mod =
```
Comment (heplesser) [inline nestkernel/conn_builder.cpp]: This could be `const`, and would suggest the following renaming:
- `synapse_model_` -> `synapse_model_id_` (because it just is the id number)
- `syn_mod`-> `synapse_model`

File: nestkernel/connection.h [hunk 6]
```diff
@@ -150,6 +150,12 @@ class Connection
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
+   * Check syn_spec dictionary for parameters that are not allowed for this
+   * connection. Will issue warning or throw error if a parameter is found.
+   */
```
Comment (heplesser) [inline nestkernel/connection.h]: See above, the base class doc should be here. Mention that the base class implementation does nothing and that classes requiring checks need to override with their own method.

File: nestkernel/connector_model.h [hunk 7]
```diff
@@ -150,6 +150,8 @@ class ConnectorModel
 
   virtual const CommonSynapseProperties& get_common_properties() const = 0;
 
+  virtual void check_synapse_params( const DictionaryDatum& ) const = 0;
```
Comment (heplesser) [inline nestkernel/connector_model.h]: Add documentation.

File: testsuite/regressiontests/issue-737-threads.sli [hunk 8]
```diff
@@ -0,0 +1,96 @@
...
+FirstVersion: May 2017
+SeeAlso: testsuite::issue-735, testsuite::issue-737
+*/
+
+(unittest) run
+/unittest using
+
+skip_if_not_threaded
+
+% Test multithreded c in syn_spec for stdp_dopamine_synapse model
```
Comment (heplesser) [inline testsuite/regressiontests/issue-737-threads.sli]: "a" missing in "multithreaded"; I think that is in other places, too.

**Comment by kappeld** [comment]
At a first glance the changes look good to me, but they will effect our custom connector model as @heplesser suggested. I will try this out and review the changes more carefully as soon as possible.

File: models/cont_delay_connection.h [hunk 9]
```diff
@@ -141,8 +141,7 @@ class ContDelayConnection : public Connection< targetidentifierT >
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
-   * Check syn_spec dictionary for parameters that are not allowed for this
-   * connection. Will issue warning or throw error if a parameter is found.
+   * Checks to see if delay is given in syn_spec.
```
Comment (heplesser) [inline models/cont_delay_connection.h]: This is a bit confusing. I would rather write `Throws exception if delays is given`. Otherwise, the reader may think that the check will throw and exception if the weight is missing.

File: models/quantal_stp_connection.h [hunk 10]
```diff
@@ -127,8 +127,7 @@ class Quantal_StpConnection : public Connection< targetidentifierT >
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
-   * Check syn_spec dictionary for parameters that are not allowed for this
-   * connection. Will issue warning or throw error if a parameter is found.
+   * Checks to see if n or a are given in syn_spec.
```
Comment (heplesser) [inline models/quantal_stp_connection.h]: Also here change the wording so that it is clear that n and a are "prohibited".

File: models/stdp_dopa_connection.h [hunk 11]
```diff
@@ -197,8 +197,11 @@ class STDPDopaConnection : public Connection< targetidentifierT >
   void set_status( const DictionaryDatum& d, ConnectorModel& cm );
 
   /**
-   * Check syn_spec dictionary for parameters that are not allowed for this
-   * connection. Will issue warning or throw error if a parameter is found.
+   * Checks to see if illegal parameters are given in syn_spec.
+   *
+   * The illegal parameters are: vt, A_minus, A_plus, Wmax, Wmin, b, tau_c,
+   * tau_n, tau_plus, c and n. The last two only apply if we have more than one
```
Comment (heplesser) [inline models/stdp_dopa_connection.h]: "only apply" -> "are prohibited only"

File: nestkernel/connection.h [hunk 12]
```diff
@@ -150,6 +150,18 @@ class Connection
...
+   * Check syn_spec dictionary for parameters that are not allowed with the
+   * given connection.
+   *
+   * Will issue warning or throw error if an illegal parameter is found. The
+   * method does nothing if no illegal parameter is found.
+   *
+   * @note Classes requiring checks need to override the function with their own
+   * implementation, as this base class implementation does not do anything.
+   */
+  void check_synapse_params( const DictionaryDatum& d ) const;
```
Comment (stinebuu) [inline nestkernel/connection.h]: @jakobj As far as I understand, the connection class is not supposed to have any virtual functions, because we then store pointers to the subclasses so we can use the correct overridden function.  By making this into an empty function, we avoid this memory allocation.

@heplesser does this sound about right?

Comment (heplesser) [inline nestkernel/connection.h]: Yes, the technical term is *vtable*: For the 4G kernel we worked hard to avoid virtual functions in `Connection` objects so that these objects do not contain a vtable-pointer, which would cost 8B per synapse; see Kunkel et al (2014) for details.

**Comment by heplesser** [comment]
Before merging, wait for feedback from @kappeld concerning the effect on module implementing its own `ConnectorModel`.

File: nestkernel/connection.h (hunk 12 above)
Comment (jakobj) [inline nestkernel/connection.h]: Ah alright, should've known that. ;) thanks for reminding me.

**Comment by kappeld** [comment]
On a related note: Since the API of NEST has changed now quite a bit since the 2.12.0 release (with this and other changes), @heplesser are you planning to issue a 2.12.1 release soon? We would like to keep the version numbers of our custom module in sync with NEST's version number. Since the changes made to NEST also require a slightly updated version of our module to be compatible, making a new minor release might be more transparent for the users.

**Comment by heplesser** [comment]
@kappeld Thanks for checking! Yes, we are considering a 2.12.1 release since there have been a number of bug fixes (and a few more under review).

**Comment by heplesser** [comment]
Release Notes: Refactored `check_synapse_param()` to better object-oriented design. `Connection` subclasses can now define their own checks.
