### PR TITLE
Correctly build connection infrastructure in GetConnections also when secondary events in use

### LINKED ISSUE #2614: GetConnections crashes simulation with gap junctions
Adding a `<< >> GetConnections` call between the final `Connect` and the `Simulate` calls in a minimal simulation with gap junctions (), leads in most runs to a segmentation fault or in some runs to NaN values for recorded membrane potential. No problems occur for a corresponding network without gap junctions, so it seems related to configuration of gap junction connection data structures. The same works fine in nest-2.14.1.

### PR DESCRIPTION
**Pull request by heplesser**
This PR fixes #2614 with a straightforward solution: `update_delay_extrema_()` and `check_wfr_use()` are now called before `update_connection_infrastructure()` also when the connection infrastructure is built by `get_connections()`.  This is necessary because if no nodes or connections are added between a `GetConnections` and a `Simulate` call, the infrastructure built by `get_connections()` is used. This requires information about the data size in secondary events, which again depends on `min_delay`.

PEP8 fixes in two unrelated files because they were detected by check_code_style.

This entire process needs to be refactored at a later stage, this is just a bug fix.

### CODE REVIEW

File: nestkernel/connection_manager.cpp [hunk 1]
```diff
@@ -976,6 +976,15 @@ nest::ConnectionManager::get_connections( const DictionaryDatum& params )
   // as this may involve sorting connections by source node IDs.
   if ( connections_have_changed() )
   {
+    // We need to update min_delay because it is used by check_wfr_use() below
+    // to set secondary event data size.
+    update_delay_extrema_();
+
+    // Check whether waveform relaxation is used on any MPI process;
+    // needs to be called before update_connection_intrastructure_since
```
Comment (nicolossus) [inline nestkernel/connection_manager.cpp:984]:
```suggestion
    // needs to be called before update_connection_infrastructure since
```

**Review by nicolossus — APPROVED** [review]
Thanks for the bug fix! Besides the minor typo, this looks good to me.

File: testsuite/unittests/test_hh_psc_alpha_gap.sli [hunk 2]
```diff
@@ -85,6 +85,9 @@ neuron1 neuron2
 Connect
 vm neuron2     1.0 h Connect
 
+% The following call to GetConnections makes Simulate crash
+% or generate results containing NaNs, see #2614.
+<< >> GetConnections ;
```
Comment (med-ayssar) [inline testsuite/unittests/test_hh_psc_alpha_gap.sli:90]: I think that it is better to create a specific test for this case rather than inserting the `GetConnection` without relay using the returned connections.

**Review by med-ayssar — APPROVED** [review]
