### PR TITLE
Generalize double and integer synapse parameters in `connect_arrays()`

### LINKED ISSUE #2285: Can't specify synapse label when using array indices and one-to-one connection rule
**Describe the bug**

It's not possible to use pass a `synapse_label` parameter in the `syn_spec` dictionary, in conjunction with the `one_to_one` rule and node ids passed as arrays. It works when nodes are passed as `NodeCollection`, but this limits some use cases where the same node should appear multiple times.

**To Reproduce**

```
import nest
neurons = nest.Create('iaf_psc_exp', 2)
nest.Connect([1], [2], conn_spec='one_to_one', syn_spec={'synapse_model': 'static_synapse_lbl', 'synapse_label': 1})
```

gives the error 
```
>> nest.lib.hl_api_exceptions.TypeMismatch: TypeMismatch in SLI function connect_arrays
```
However, the following works:
```
neurons = nest.Create('iaf_psc_exp', 2)
nest.Connect(nest.NodeCollection([1]), nest.NodeCollection([2]),
             conn_spec='one_to_one', syn_spec={'synapse_model': 'static_synapse_lbl', 'synapse_label': 1})
```
Removing the synapse_label parameter also works.

**Expected behavior**

Connection should be successful.

**Desktop/Environment (please complete the following information):**
[cmake_summary.txt](https://github.com/nest/nest-simulator/files/7990166/cmake_summary.txt)

 - OS: Linux Mint 19.3, kernel 5.4.0-050400-generic
 - Python-Version: 3.9.0
 - NEST-Version: 3.2
 - Installation: manual install inside Miniconda env, see attached file.

### PR DESCRIPTION
**Pull request by hakonsbm**
Synapse parameters in `connect_arrays()` are now checked against the default values for that synapse model, and stored in a SLI `Dictionary` with the correct type. Fixes #2285.

### CODE REVIEW

File: nestkernel/connection_manager.cpp [hunk 1]
```diff
@@ -578,39 +578,51 @@ nest::ConnectionManager::connect_arrays( long* sources,
   sw_construction_connect.start();
 
   // Mapping pointers to the first parameter value of each parameter to their respective names.
-  std::map< Name, double* > param_pointers;
+  // The bool is whether the value is an integer or not, which is determined at a later point.
```
Comment (stinebuu) [inline nestkernel/connection_manager.cpp:581]:
```suggestion
  // The bool indicates whether the value is an integer or not, and is determined at a later point.
```

**Review by mlober — APPROVED** [review]
Sorry for approving so late, I did not realize I was a reviewer until now. Everything looks good to me.
