### PR TITLE
Avoid segfault when using a weight recorder with a probabilistic synapse

### LINKED ISSUE #1212: Segmentation fault with probabilistic synapse and weight recording
Description of problem:
When the 'weight_recorder' model is used with probabilistic synapses (e.g. 'bernoulli_synapse'), a segmentation fault occurs. This may be caused by the fact that probabilistic synapses can randomly drop spikes, causing the `e.set_receiver` function of the  `Event ` instance to never be called, thus leaving the receiver attribute uninitialized. When creating an associated `WeightRecorderEvent` instance if a weight recorder is present for the synapse model, the `ConnectorBase::send_weight_event` function seems to ignore that the event was not actually sent to the postsynaptic target and the receiver properly configured.

Version-Release or Git commit:
NEST Version 2.14.0

How reproducible: (Always/Sometimes/Unsure)
Always

Steps to Reproduce:

Run this script
```python
import nest

if __name__ == "__main__":

    # Source neuron
    input_generator = nest.Create("poisson_generator", params={"rate": 50.})
    input = nest.Create("parrot_neuron", 1)
    nest.Connect(input_generator, input)
    
    # Target neuron
    output = nest.Create("parrot_neuron")
    
    # Probabilistic synapse with weight recording
    wr = nest.Create('weight_recorder')
    nest.CopyModel('bernoulli_synapse', 'bernoulli_synapse_wr', {'weight_recorder': wr[0]})
    nest.Connect(input, output, 'one_to_one', syn_spec={'model': 'bernoulli_synapse_wr',
                                                        'p_transmit': 0.5,
                                                        'weight': 1.0,
                                                        })

    # Simulate for a few seconds
    nest.Simulate(10000.)
    dwr = nest.GetStatus(wr)[0]
    print('Number of recorded events: %d' % (len(dwr["events"]["weights"])))
```

Actual results:

```
              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Mar  6 2019 21:51:15

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'nest.help()' to find out more about NEST.

Jun 03 00:53:58 NodeManager::prepare_nodes [Info]: 
    Preparing 4 nodes for simulation.

Jun 03 00:53:58 SimulationManager::start_updating_ [Info]: 
    Number of local nodes: 4
    Simulaton time (ms): 10000
    Number of OpenMP threads: 1
    Number of MPI processes: 1
[computer:12065] *** Process received signal ***
[computer:12065] Signal: Segmentation fault (11)
[computer:12065] Signal code: Address not mapped (1)
[computer:12065] Failing at address: 0x8
[computer:12065] [ 0] /lib/x86_64-linux-gnu/libpthread.so.0(+0x13150)[0x7f9942504150]
[computer:12065] [ 1] /home/user/myproject/lib/libmodels.so(+0x240212)[0x7f9935483212]
[computer:12065] [ 2] /home/user/myproject/lib/libnestkernel.so(_ZN4nest20EventDeliveryManager14deliver_eventsEi+0x2db)[0x7f9935169c6b]
[computer:12065] [ 3] /home/user/myproject/lib/libnestkernel.so(+0xc38a3)[0x7f993514c8a3]
[computer:12065] [ 4] /home/user/myproject/lib/libgomp.so.1(GOMP_parallel+0x3f)[0x7f993482bfca]
[computer:12065] [ 5] /home/user/myproject/lib/libnestkernel.so(_ZN4nest17SimulationManager7update_Ev+0x147)[0x7f993514a6b7]
[computer:12065] [ 6] /home/user/myproject/lib/libnestkernel.so(_ZN4nest17SimulationManager12call_update_Ev+0x58f)[0x7f993514b7ef]
[computer:12065] [ 7] /home/user/myproject/lib/libnestkernel.so(_ZN4nest17SimulationManager3runERKNS_4TimeE+0x1cd)[0x7f99351503bd]
[computer:12065] [ 8] /home/user/myproject/lib/libnestkernel.so(_ZN4nest17SimulationManager8simulateERKNS_4TimeE+0x1e)[0x7f993515051e]
[computer:12065] [ 9] /home/user/myproject/lib/libnestkernel.so(_ZN4nest8simulateERKd+0xc3)[0x7f99351335b3]
[computer:12065] [10] /home/user/myproject/lib/libnestkernel.so(_ZNK4nest10NestModule16SimulateFunction7executeEP14SLIInterpreter+0x45)[0x7f993510a025]
[computer:12065] [11] /home/user/myproject/lib/libsli.so(+0x733f3)[0x7f9934f813f3]
[computer:12065] [12] /home/user/myproject/lib/libsli.so(_ZN14SLIInterpreter8execute_Em+0x222)[0x7f9934f85d42]
[computer:12065] [13] /home/user/myproject/lib/libsli.so(_ZN14SLIInterpreter7executeERKNSt7__cxx1112basic_stringIcSt11char_traitsIcESaIcEEE+0x162)[0x7f9934f862e2]
[computer:12065] [14] /home/user/myproject/lib/python3.6/site-packages/nest/pynestkernel.so(+0x3a369)[0x7f9935b4a369]
[computer:12065] [15] /home/user/myproject/bin/python3.6(_PyCFunction_FastCallDict+0x115)[0x55eb1057e705]
[computer:12065] [16] /home/user/myproject/bin/python3.6(+0x19842c)[0x55eb1060542c]
[computer:12065] [17] /home/user/myproject/bin/python3.6(_PyEval_EvalFrameDefault+0x30a)[0x55eb1062a38a]
[computer:12065] [18] /home/user/myproject/bin/python3.6(+0x19253b)[0x55eb105ff53b]
[computer:12065] [19] /home/user/myproject/bin/python3.6(+0x198505)[0x55eb10605505]
[computer:12065] [20] /home/user/myproject/bin/python3.6(_PyEval_EvalFrameDefault+0x30a)[0x55eb1062a38a]
[computer:12065] [21] /home/user/myproject/bin/python3.6(PyEval_EvalCodeEx+0x329)[0x55eb10600289]
[computer:12065] [22] /home/user/myproject/bin/python3.6(+0x1941a6)[0x55eb106011a6]
[computer:12065] [23] /home/user/myproject/bin/python3.6(PyObject_Call+0x3e)[0x55eb1057e54e]
[computer:12065] [24] /home/user/myproject/bin/python3.6(_PyEval_EvalFrameDefault+0x19ec)[0x55eb1062ba6c]
[computer:12065] [25] /home/user/myproject/bin/python3.6(+0x191a76)[0x55eb105fea76]
[computer:12065] [26] /home/user/myproject/bin/python3.6(+0x192771)[0x55eb105ff771]
[computer:12065] [27] /home/user/myproject/bin/python3.6(+0x198505)[0x55eb10605505]
[computer:12065] [28] /home/user/myproject/bin/python3.6(_PyEval_EvalFrameDefault+0x30a)[0x55eb1062a38a]
[computer:12065] [29] /home/user/myproject/bin/python3.6(PyEval_EvalCodeEx+0x329)[0x55eb10600289]
[computer:12065] *** End of error message ***
```

Expected results:

```
              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Mar  6 2019 21:51:15

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'nest.help()' to find out more about NEST.

Jun 03 01:01:08 NodeManager::prepare_nodes [Info]: 
    Preparing 4 nodes for simulation.

Jun 03 01:01:08 SimulationManager::start_updating_ [Info]: 
    Number of local nodes: 4
    Simulaton time (ms): 10000
    Number of OpenMP threads: 1
    Number of MPI processes: 1

Jun 03 01:01:08 SimulationManager::resume [Info]: 
    Simulation finished.
Number of recorded events: <ANY NUMBER>
```

Additional info:

gdb backtrace
```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff441b700 (LWP 6858)]
[New Thread 0x7ffff1c1a700 (LWP 6859)]
[New Thread 0x7ffff1419700 (LWP 6860)]
[Thread 0x7ffff1419700 (LWP 6860) exited]
[Thread 0x7ffff1c1a700 (LWP 6859) exited]
[Thread 0x7ffff441b700 (LWP 6858) exited]
[New Thread 0x7ffff1419700 (LWP 6896)]
[New Thread 0x7ffff1c1a700 (LWP 6898)]
[INFO] [2019.6.3 1:7:16 /home/user/myproject/lib/nest/nest-simulator/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2019.6.3 1:7:16 /home/user/myproject/lib/nest/nest-simulator/nestkernel/rng_manager.cpp:233 @ Network::create_rngs_] : Deleting existing random number generators
[INFO] [2019.6.3 1:7:16 /home/user/myproject/lib/nest/nest-simulator/nestkernel/rng_manager.cpp:238 @ Network::create_rngs_] : Creating default RNGs
[INFO] [2019.6.3 1:7:16 /home/user/myproject/lib/nest/nest-simulator/nestkernel/rng_manager.cpp:284 @ Network::create_grng_] : Creating new default global RNG

              -- N E S T --

  Copyright (C) 2004 The NEST Initiative
  Version 2.14.0 Mar  6 2019 21:51:15

This program is provided AS IS and comes with
NO WARRANTY. See the file LICENSE for details.

Problems or suggestions?
  Visit http://www.nest-simulator.org

Type 'nest.help()' to find out more about NEST.

Jun 03 01:07:16 NodeManager::prepare_nodes [Info]: 
    Preparing 4 nodes for simulation.

Jun 03 01:07:16 SimulationManager::start_updating_ [Info]: 
    Number of local nodes: 4
    Simulaton time (ms): 10000
    Number of OpenMP threads: 1
    Number of MPI processes: 1

Thread 1 "python" received signal SIGSEGV, Segmentation fault.
0x00007fffeab50212 in nest::ConnectorBase::send_weight_event(nest::CommonSynapseProperties const&, nest::Event const&, int) [clone .part.94] ()
   from /home/user/myproject/lib/libmodels.so
(gdb) backtrace
#0  0x00007fffeab50212 in nest::ConnectorBase::send_weight_event(nest::CommonSynapseProperties const&, nest::Event const&, int) [clone .part.94] ()
   from /home/user/myproject/lib/libmodels.so
#1  0x00007fffea836c6b in nest::EventDeliveryManager::deliver_events(int) () from /home/user/myproject/lib/libnestkernel.so
#2  0x00007fffea8198a3 in nest::SimulationManager::update_() [clone ._omp_fn.0] () from /home/user/myproject/lib/libnestkernel.so
#3  0x00007fffe9ef8fca in GOMP_parallel (fn=0x7fffea819760 <nest::SimulationManager::update_() [clone ._omp_fn.0]>, data=0x7fffffffb400, num_threads=1, flags=0)
    at /opt/conda/conda-bld/compilers_linux-64_1534514838838/work/.build/x86_64-conda_cos6-linux-gnu/src/gcc/libgomp/parallel.c:168
#4  0x00007fffea8176b7 in nest::SimulationManager::update_() () from /home/user/myproject/lib/libnestkernel.so
#5  0x00007fffea8187ef in nest::SimulationManager::call_update_() () from /home/user/myproject/lib/libnestkernel.so
#6  0x00007fffea81d3bd in nest::SimulationManager::run(nest::Time const&) () from /home/user/myproject/lib/libnestkernel.so
#7  0x00007fffea81d51e in nest::SimulationManager::simulate(nest::Time const&) () from /home/user/myproject/lib/libnestkernel.so
#8  0x00007fffea8005b3 in nest::simulate(double const&) () from /home/user/myproject/lib/libnestkernel.so
#9  0x00007fffea7d7025 in nest::NestModule::SimulateFunction::execute(SLIInterpreter*) const () from /home/user/myproject/lib/libnestkernel.so
#10 0x00007fffea64e3f3 in FunctionDatum::execute(SLIInterpreter*) () from /home/user/myproject/lib/libsli.so
#11 0x00007fffea652d42 in SLIInterpreter::execute_(unsigned long) () from /home/user/myproject/lib/libsli.so
#12 0x00007fffea6532e2 in SLIInterpreter::execute(std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> > const&) () from /home/user/myproject/lib/libsli.so
#13 0x00007fffeb217369 in __pyx_pw_12pynestkernel_10NESTEngine_7run(_object*, _object*) () from /home/user/myproject/lib/python3.6/site-packages/nest/pynestkernel.so
#14 0x0000555555665705 in _PyCFunction_FastCallDict () at /tmp/build/80754af9/python_1546130271559/work/Objects/methodobject.c:209
#15 0x00005555556ec42c in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4851
#16 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#17 0x00005555556e653b in _PyFunction_FastCall (globals=<optimized out>, nargs=1, args=<optimized out>, co=<optimized out>) at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4933
#18 fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4968
#19 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#20 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#21 0x00005555556e7289 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>, kwargs=0x7ffff7fb0068, 
    kwnames=0x7ffff7fb0060, argcount=<optimized out>, args=0x7fffeb5a2ab0, locals=0x0, globals=<optimized out>, _co=0x7fffeb2756f0) at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#22 PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
---Type <return> to continue, or q <return> to quit---
#23 0x00005555556e81a6 in function_call () at /tmp/build/80754af9/python_1546130271559/work/Objects/funcobject.c:604
#24 0x000055555566554e in PyObject_Call () at /tmp/build/80754af9/python_1546130271559/work/Objects/abstract.c:2261
#25 0x0000555555712a6c in do_call_core (kwdict=0x7ffff7f25a68, callargs=0x7ffff7e920b8, func=0x7fffe91df598) at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:5120
#26 _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3404
#27 0x00005555556e5a76 in _PyEval_EvalCodeWithName () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#28 0x00005555556e6771 in fast_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4992
#29 0x00005555556ec505 in call_function () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4872
#30 0x000055555571138a in _PyEval_EvalFrameDefault () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:3335
#31 0x00005555556e7289 in _PyEval_EvalCodeWithName (qualname=0x0, name=<optimized out>, closure=0x0, kwdefs=0x0, defcount=0, defs=0x0, kwstep=2, kwcount=<optimized out>, kwargs=0x0, kwnames=0x0, argcount=0, 
    args=0x0, locals=0x7ffff7f612d0, globals=0x7ffff7f612d0, _co=0x7ffff7f22c00) at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4166
#32 PyEval_EvalCodeEx () at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:4187
#33 0x00005555556e801c in PyEval_EvalCode (co=co@entry=0x7ffff7f22c00, globals=globals@entry=0x7ffff7f612d0, locals=locals@entry=0x7ffff7f612d0)
    at /tmp/build/80754af9/python_1546130271559/work/Python/ceval.c:731
#34 0x000055555576a3c4 in run_mod () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:1025
#35 0x000055555576a7c1 in PyRun_FileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:978
#36 0x000055555576a9c3 in PyRun_SimpleFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:419
#37 0x000055555576aacd in PyRun_AnyFileExFlags () at /tmp/build/80754af9/python_1546130271559/work/Python/pythonrun.c:81
#38 0x000055555576e4b3 in run_file (p_cf=0x7fffffffc84c, filename=0x5555558a9580 L"main_wr_segfault.py", fp=0x55555594b650) at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:340
#39 Py_Main () at /tmp/build/80754af9/python_1546130271559/work/Modules/main.c:811
#40 0x000055555563702e in main () at /tmp/build/80754af9/python_1546130271559/work/Programs/python.c:69
#41 0x00007ffff77f71c1 in __libc_start_main (main=0x555555636f40 <main>, argc=2, argv=0x7fffffffca58, init=<optimized out>, fini=<optimized out>, rtld_fini=<optimized out>, stack_end=0x7fffffffca48)
    at ../csu/libc-start.c:308
#42 0x0000555555717e0e in _start () at ../sysdeps/x86_64/elf/start.S:103
```

### PR DESCRIPTION
**Pull request by hakonsbm**
This PR fixes an issue caused by using a weight recorder with a probabilistic synapse. If the synapse drops a spike, i.e. the spike is not transmitted, the receiving node of the `Event` object is never set. When the connector then tries to create a `WeightRecorderEvent` from the `Event`, it causes a segfault. The connector now checks that the receiver node is set in the event before it tries to create a `WeightRecorderEvent`.

Fixes #1212.

### CODE REVIEW

File: nestkernel/event.h [hunk 1]
```diff
@@ -258,6 +258,16 @@ class Event
    */
   virtual void set_diffusion_factor( weight t ){};
 
+  /**
+   * Returns true if the pointer to the sender node is not null.
+   */
+  bool sender_is_not_null() const;
```
Comment (heplesser) [inline nestkernel/event.h]: This is fine, but I wonder if we shouldn't use a positive name, e.g., `sender_valid()`, same for receiver.

File: nestkernel/event.h [hunk 2]
```diff
@@ -258,6 +258,16 @@ class Event
...
+
+  /**
+   * Returns true if the pointer to the receiver node is not null.
+   */
+  bool receiver_is_not_null() const;
```
Comment (heplesser) [inline nestkernel/event.h]: See comment on sender method.

File: nestkernel/event.h (hunk 1 above)
Comment (hakonsbm) [reply nestkernel/event.h]: @heplesser My reasoning behind this name was to avoid having to use `not` everywhere these functions were used. But I agree that positive names look better, so I have changed them now.
