### PR TITLE
Correct documentation for aeif_psc models

### LINKED ISSUE #2486: AdEx equations incorrect for current-based models
**Describe the flaw**
The equations describing the evolution of the membrane potential of the current-based AdEx models appear to be incorrect. The synaptic currents are described in terms of conductances and dependent on the voltage. This should hold for the conductance-based versions, but not the current-based ones.
Affected models are: aeif_psc_delta (here the current is correct, but not in the voltage equation), aeif_psc_exp, aeif_psc_alpha.

**Suggest an improvement**
I suggest either using a more general formalism with only I_syn and/or correct and detail the form of the postsynaptic current. 

**Supporting materials**
Screenshot from 2022-09-30 18-23-39

**Desktop/Environment**
n/a
**Additional context**
n/a

### PR DESCRIPTION
**Pull request by heplesser**
This corrects documentation for current-based AEIF neurons anf fixes #2486.

### CODE REVIEW

**Review by jessica-mitchell — APPROVED** [review]
@heplesser lgtm!

File: models/aeif_psc_exp.h [hunk 1]
```diff
@@ -78,19 +78,19 @@ The membrane potential is given by the following differential equation:
...
 
- C dV/dt= -g_L(V-E_L)+g_L\cdot\Delta_T\cdot\exp((V-V_T)/\Delta_T)-g_e(t)(V-E_e) \\
-                                                     -g_i(t)(V-E_i)-w +I_e
+ C dV/dt= -g_L(V-E_L)+g_L\cdot\Delta_T\cdot\exp((V-V_T)/\Delta_T) - w(t) + I_{syn}(t) + I_e
 
 and
 
 .. math::
 
  \tau_w \cdot dw/dt= a(V-E_L) -W
```
Comment (zbarni) [inline models/aeif_psc_exp.h:87]: Should be lower case `w` and a space?

**Review by zbarni — COMMENTED** [review]
Other than the one comment, it looks good to me as well.

File: models/aeif_psc_exp.h (hunk 1 above)
Comment (heplesser) [reply models/aeif_psc_exp.h]: Fixed!

**Comment by heplesser** [comment]
@zbarni Could you re-review, approve if you are happy and resolve the conversation if it does not get resolved automatically by approving?

**Review by zbarni — APPROVED** [review]
Done!

**Review by zbarni — APPROVED** [review]

File: models/aeif_psc_exp.h (hunk 1 above)
Comment (zbarni) [reply models/aeif_psc_exp.h]: Not sure how to actually do this, the "Resolve conversation" button seems to be missing..
