### PR TITLE
Avoid MPI deadlocks on SynapseCollection.get()/set()

### LINKED ISSUE #3099: NEST hangs when setting connection weight in parallel simulations
The tests below will pass if run serially, but hang when run with `mpirun -np 2 pytest ...`. This also holds if only one of the three tests is executed. Usually, one MPI process will report success while the other never completes. Note that for two processes, only one will actually have the connection. Presumably, this leads to incorrect MPI communication, where one rank hangs.

This PR is based on a bug report by Xavier Otzau on the NEST User Mailing List.

```python
import nest
import pytest


@pytest.fixture
def conns():
    nest.ResetKernel()
    nrn = nest.Create('parrot_neuron')
    nest.Connect(nrn, nrn)
    return nest.GetConnections()

def test_conn_weight(conns):
    if conns:
        conns.weight = 2.5

def test_set_weight(conns):
    if conns:    
        conns.set({'weight': 2.5})

def test_set_status_weight(conns):
    if conns:
        nest.SetStatus(conns, 'weight', 2.5)
```

### PR DESCRIPTION
**Pull request by heplesser**
This fixes #3099. MPI deadlocks could occur if only some MPI ranks performed `get()` or `set()` operations on `SynapseCollection`s. These operations are local operations so while not elegant, they should work even if executed only on some ranks and not on other, e.g., when a rank has no connections.

The hang occurred because the `get()`/`set()` methods called `GetKernelStatus()` to check for the number of connections to decide whether an SC was still valid. This was misguided to begin with, since the number of connections is only known locally. This is now changed to use the network size, whose global value is locally known. For a proposed proper solution, see #3100.

A further problem then was that `GetKernelStatus()` called `ConnectionManager::update_delay_extrema_()`, which unconditionally performed MPI exchange of `min/max_delay`. This PR changes this so that delay extrema are MPI-exchanged only if their values could have changed remotely. This also eliminates the MPI communication hidden in every single `nest.<some property>` use and might thus lead to faster execution of simulation scripts.

The test simply checks that it does not time out.

### CODE REVIEW

File: nestkernel/connection_manager.cpp [hunk 1]
```diff
@@ -464,6 +464,13 @@ nest::ConnectionManager::connect( TokenArray sources, TokenArray targets, const
 void
 nest::ConnectionManager::update_delay_extrema_()
 {
+  if ( kernel().simulation_manager.has_been_simulated() )
+  {
+    // Once simulation has started, min/max_delay can no longer change,
+    // so there is nothing to update.
+    return;
+  }
```
Comment (nicolossus) [inline nestkernel/connection_manager.cpp:472]: @heplesser In `ConnectionManager::get_connections()` there is a call to `update_delay_extrema_()` if `connections_have_changed`. It seems like it is used for setting the secondary event data size. I'm not sure if your change affect this, so I just wanted to check if you are aware and have taken that into consideration with the change?

File: testsuite/pytests/mpi/2/test_issue_3099.py [hunk 2]
```diff
@@ -0,0 +1,53 @@
...
+@pytest.fixture
+def conns():
+    nest.ResetKernel()
+    nrn = nest.Create("parrot_neuron")
+    nest.Connect(nrn, nrn)
+    return nest.GetConnections()
+
+
+def test_conn_weight(conns):
+    """Test that operation does cause MPI deadlock."""
```
Comment (nicolossus) [inline testsuite/pytests/mpi/2/test_issue_3099.py:36]:
```suggestion
    """Test that operation does not cause MPI deadlock."""
```
Since the test should fail if a deadlock happens, a negation is more correct I think. Also applies to the docstrings below.

**Review by nicolossus — APPROVED** [review]
@heplesser LGTM. I have some minor comments/clarifications, but I'll go ahead and approve.

**Review by otcathatsya — APPROVED** [review]

File: nestkernel/connection_manager.cpp (hunk 1 above)
Comment (heplesser) [reply nestkernel/connection_manager.cpp:472]: Thanks for pointing this out, but this is safe:  `update_delay_extrema()`  is called at least once while `has_been_simulated()` is still false, so we will get the correct min/max values.

File: testsuite/pytests/mpi/2/test_issue_3099.py [hunk 3]
```diff
@@ -0,0 +1,53 @@
...
+
+def test_conn_weight(conns):
+    """Test that operation does not cause MPI deadlock."""
+
+    if conns:
+        conns.weight = 2.5
+
+
+def test_set_weight(conns):
+    """Test that operation does cause MPI deadlock."""
```
Comment (heplesser) [inline testsuite/pytests/mpi/2/test_issue_3099.py:43]:
```suggestion
    """Test that operation does not cause MPI deadlock."""
```

File: testsuite/pytests/mpi/2/test_issue_3099.py [hunk 4]
```diff
@@ -0,0 +1,53 @@
...
+
+    if conns:
+        conns.set({"weight": 2.5})
+
+
+def test_set_status_weight(conns):
+    """Test that operation does cause MPI deadlock."""
```
Comment (heplesser) [inline testsuite/pytests/mpi/2/test_issue_3099.py:50]:
```suggestion
    """Test that operation does not cause MPI deadlock."""
```
